spring:
  datasource:
    url: spring.datasource.url=jdbc:mysql://localhost:3306/devhome?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

   